### ISSUE TITLE
setup travis-ci integration

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#39] opened 2019-04-08 22:11 UTC
**Feature description**
Setup and activate travis-ci for this project

- [x] Add file `travis.yml`
    - [x] Configure it
- [x] Activate travis-ci integration

**Comment by olemis** [comment] 2019-07-28 01:01
duplicate of #68

**Closed as completed by olemis** 2019-07-28 01:01 UTC
Labels: help wanted, good first issue, stdev, wip
