### ISSUE TITLE
Black windows when wallet run connected  to a network without internet access.

### ISSUE THREAD

**Issue by hsequeda** [fibercrypto/FiberCryptoWallet#262] opened 2019-11-27 17:10 UTC
**Describe the bug**
When I run the application connected to a network without Internet access, it does not load completely. Instead, it shows a black window and in the console it constantly shows the message "INFO [Skycoin Account]: POST / api / v1 / outputs? Addrs = xxx".

**Environment information:**
- OS: Linux 
- Platform: Linux 4.17.0-041700rc4-generic x86_64

**Steps to Reproduce**

1. Connect to a network without internet connection
2. Run "make run"  command or "./deploy/linux/FiberCryptoWallet" if it's builded.
3. See error

**Actual behavior**
![Captura de pantalla de 2019-11-27 12-01-45](https://user-images.githubusercontent.com/46435362/69744461-37b45180-110e-11ea-82de-587f3ec5c5e6.png)
![Captura de pantalla de 2019-11-27 12-01-59](https://user-images.githubusercontent.com/46435362/69744503-4c90e500-110e-11ea-9ea7-1595adb80f78.png)

**Possible implementation**
It is possible that the problem is at the endpoint /api/v1/outputs.

**Comment by olemis** [comment] 2020-01-10 06:26
duplicate of #295

**Closed as completed by olemis** 2020-01-10 06:26 UTC
Labels: bug
